name: Daily Update - Recent Posts

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.2

    - name: Set up Python
      uses: actions/setup-python@v2.3.2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install octokit
        pip freeze > requirements.txt

    - name: Run main.py
      run: python main.py > output.txt

    - name: Run Python script
      run: |
        import octokit
        import os

        client = octokit.Client(access_token=os.environ["TOKEN"])

        repository = os.environ["Recent-Posts-from-MyTechBlog"]
        owner, repo = repository.split("/")

        issue_title = "Recent Posts updated"
        issue_body = fs.readFileSync('output.txt', 'utf8');

        issue = client.issues.create(
            owner, repo,
            title=issue_title,
            body=issue_body
        )

        print("Issue created with ID:", issue.number)