name: Get Recent Post

on:
  schedule:
    - cron: '5 * * * *' # Run every minute

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.2

    - name: Set up Python
      uses: actions/setup-python@v2.3.2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip freeze > requirements.txt

    - name: Execute main.py
      run: |
        python main.py

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v4
      with:
        add: 'README.md'
        commit_message: '$(date "+%Y-%m-%d %H:%M:%S") | Update README with recent posts'
        push: true

    - name: Load Github Token
      run: echo "${{ secrets.GITHUB_TOKEN }}" > data
